version: "3"
name: "mvd-with-azure"
services:

  # EDC Connector to simulate a dataspace participant acting as a data provider which is located in EU.
  lieferant1:
    container_name: lieferant1
    build:
      context: ../../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    env_file:
      - lieferant1.env
    depends_on:
      - registration-service
    ports:
      - "9191:9191"
      - "8181:8181"
      - "5005:5005"
      - "7171:7171"
    volumes:
      - ../resources/self-description/lieferant1:/resources

  # EDC Connector to simulate a dataspace participant acting as a data consumer which is located in EU.
  lieferant2:
    container_name: lieferant2
    build:
      context: ../../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
    env_file:
      - lieferant2.env
    depends_on:
      - registration-service
    ports:
      - "9192:9191"
      - "8182:8181"
      - "5006:5006"
      - "7172:7171"
    volumes:
      - ../resources/self-description/lieferant2:/resources

  # EDC Connector to simulate a dataspace participant acting as a consumer which is located in US.
  vnb:
    container_name: vnb
    build:
      context: ../../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007"
    env_file:
      - vnb.env
    depends_on:
      - registration-service
    ports:
      - "9193:9191"
      - "8183:8181"
      - "5007:5007"
      - "7173:7171"
    volumes:
      - ../resources/self-description/vnb:/resources


  # Dataspace registration service authority.
  registration-service:
    container_name: registration-service
    build:
      #e.g. /home/user/RegistrationService/launcher
      context: ../../../launchers/registrationservice
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008"
    env_file: reg.env

    ports:
      - "8184:8184"
      - "8185:8181"
      - "5008:5008"
      - "7174:7171"
    volumes:
      - ../resources/self-description/registration-service:/resources

  # Data Dashboard (MVD UI) for participant lieferant1
  lieferant1-datadashboard:
    container_name: lieferant1-datadashboard
    build:
      context: ${MVD_UI_PATH}
    volumes:
      - ../resources/appconfig/lieferant1:/usr/share/nginx/html/assets/config
    depends_on:
      lieferant1:
        condition: service_healthy
    ports:
      - "7080:80"
    profiles: [ "ui" ]

    # Data Dashboard (MVD UI) for participant lieferant2

  lieferant2-datadashboard:
    container_name: lieferant2-datadashboard
    build:
      context: ${MVD_UI_PATH}
    volumes:
      - ../resources/appconfig/lieferant2:/usr/share/nginx/html/assets/config
    depends_on:
      lieferant2:
        condition: service_healthy
    ports:
      - "7081:80"
    profiles: [ "ui" ]

  # Data Dashboard (MVD UI) for participant VNB
  vnb-datadashboard:
    container_name: vnb-datadashboard
    build:
      context: ${MVD_UI_PATH}
    volumes:
      - ../resources/appconfig/vnb:/usr/share/nginx/html/assets/config
    depends_on:
      vnb:
        condition: service_healthy
    ports:
      - "7082:80"
    profiles: [ "ui" ]
