@startuml
autonumber "<b>0'.'"
box "lieferant1" #LightBlue
Participant "lieferant1\nEDC" as lieferant1
Participant "lieferant1\nDID Document" as DID1
Participant "lieferant1\nIdentity Hub" as IDHUB1
end box
box "Dataspace Authority" #LightYellow
Participant "Dataspace\nDID Document" as DID0
Participant "Registration Service" as RAPI
Database "Participants\nStore" as Registry
end box
box "lieferant2 (, 3, etc.)" #LightCyan
Participant "lieferant2\nDID Document" as DID2
Participant "lieferant2\nEDC" as lieferant2
end box

lieferant1 -> DID0: Get registry endpoint
lieferant1 -> RAPI ++: List participants:\n - DID JWS\n - Hub Token
activate lieferant1
group authorize request [Distributed authorization sub-flow]
  RAPI -> DID1
  RAPI -> IDHUB1
end
RAPI -> RAPI: apply access policy
RAPI -> Registry: query participants
return participants (list of DID URIs)
lieferant1 -> DID2: Get DID Document (contains URL of lieferant2 EDC Catalog Endpoint)
deactivate lieferant1

@enduml